### ISSUE TITLE
HDBC-postgresql uses system timezone and cannot parse all timestamps

### ISSUE THREAD

**Issue by ysangkok** [flipstone/orville#131]
Tests fail on LTS 6 and 14, I didn't try the others.

Here are the failed tests for LTS 14:

```
    Insert and find many:                                               FAIL
      Exception: Convertible: error converting source data SqlString "1800-12-24 17:23:24-06:36:36" of type SqlValue to type ZonedTime: Cannot parse using default format string "%Y-%m-%d %T%Q %z"
      CallStack (from HasCallStack):
        error, called at ./Data/Convertible/Base.hs:66:17 in convertible-1.1.1.0-7i96jmLhDws8ECMxJRs7xM:Data.Convertible.Base
    Update:                                                             FAIL
      Exception: Convertible: error converting source data SqlString "1800-12-24 17:23:24-06:36:36" of type SqlValue to type ZonedTime: Cannot parse using default format string "%Y-%m-%d %T%Q %z"
      CallStack (from HasCallStack):
        error, called at ./Data/Convertible/Base.hs:66:17 in convertible-1.1.1.0-7i96jmLhDws8ECMxJRs7xM:Data.Convertible.Base
```

```
  ConduitTest
    selectConduit can read all result rows:                             FAIL
      Exception: Convertible: error converting source data SqlString "1800-12-24 17:23:24-06:36:36" of type SqlValue to type ZonedTime: Cannot parse using default format string "%Y-%m-%d %T%Q %z"
      CallStack (from HasCallStack):
        error, called at ./Data/Convertible/Base.hs:66:17 in convertible-1.1.1.0-7i96jmLhDws8ECMxJRs7xM:Data.Convertible.Base
    streamPages can read all result rows:                               FAIL
      Exception: Convertible: error converting source data SqlString "1800-12-24 17:23:24-06:36:36" of type SqlValue to type ZonedTime: Cannot parse using default format string "%Y-%m-%d %T%Q %z"
      CallStack (from HasCallStack):
        error, called at ./Data/Convertible/Base.hs:66:17 in convertible-1.1.1.0-7i96jmLhDws8ECMxJRs7xM:Data.Convertible.Base
```

I'd be happy to provide more information, but I dunno what to provide. And I dunno if they are supposed to work on PostgreSQL 13, since I think Schmods is on <s>12</s>? *edit: it is on 9.6.6*

**Comment by telser** [comment]
I replaced the postgres image in the docker-compose file with postgres:13.0 and did ` docker-compose run --rm dev ./test-loop stack-lts-14.0.yml` but didn't get the errors you reported. 

Is this what you did to get the failures?

If not, can you try that and see if you get the same thing? I'm wondering if this is the result of something changing in the server running a new version or if there is a change in something on the client side.

**Comment by ysangkok** [comment]
I was running the test suite outside docker (didn't realize the docker-compose had a database in there also). Inside the container there is no problem.

The issue appears because I have my system time zone set to `America/Mexico_City` and the test suite uses timestamps from 1800, which is probably from before Mexico introduced time zones. So the timestamp (even with timezone!) uses a calculated offset `-06:36:36`, probably derived using the longitude. HDBC-postgresql cannot parse that. I have [reported the issue to HDBC-postgresql](https://github.com/hdbc/hdbc-postgresql/issues/55). I suggest we close this unless you think Orville should have a workaround of setting the timezone to UTC on session opening. Do you think that makes sense or not? Docker containers usually have the timezone set to UTC. But I think the library should also work outside docker.

I also think the issue will be solved when using libpq? Since then HDBC's decoder won't be used.

**Comment by ysangkok** [comment]
Closing this because the hdbc-postgresql maintainer seems receptive to fixing it there.

**Comment by telser** [comment]
There are a few things here so going to do my best to unpack them all.

I think we should definitely be able to run outside of any particularly container system. And having tests that depend on something implicit like the system timezone, seems bad. I suspect that this is really some interplay between `time` and postgresql. I'd be really curious to know if that offset works in postgresql in general. Being able to set the session timezone is a good feature to keep in mind for the LibPQ version and we could make sure our tests use that to be consistent across environments.

For your last question, I think the issue won't be solved with libpq, at least not without some other work, but I would be interested in seeing a reproduction on that code.

**Comment by ysangkok** [comment]
@telser

> I suspect that this is really some interplay between time and postgresql.

Right! Did you see the issue I linked at hdbc-postgresql? They are using a format specifier for the `time` library which doesn't accept second-granular offsets. I asked a question about it on StackOverflow yesterday, and it [seems like it will be difficult to fix](https://stackoverflow.com/a/68158939/309483). But in the linked issue, it seems that the HDBC-postgresql maintainer (also in Austin btw) even says he would accept defaulting to UTC. In that case, these weird offsets wouldn't be generated at all (you'd have to input them manually, I guess?)  So that is my current plan, maybe I'll report a `time` library issue first, to see if they'd add another format specifier. But even if they did (would require redefining offsets, apparently), our compatibility constraints wouldn't be able to rely on that...

>  we could make sure our tests use that [setting session timezone]

Right, agreed! The reproduction is easy, since it just requires setting the session timezone, which only requires being able to issue arbitrary SQL on the session. I can make an orville-variant of the sample program in the linked issue, if you'd like. But it would fail currently, better fix it there first, no?

> I think the issue won't be solved with libpq

Surely since the time-parsing code wouldn't be from hdbc-postgresql with the libpq version. So if separate parsing code is used, I don't know if it would even use printf-style time parsing? I don't know the timestamptz wire protocol. The correct parsing code could look completely different. Since the involved code is completely different, I think it makes sense to have a separate issue for it.

> I'd be really curious to know if that offset works in postgresql in general. 

The offset is coming *back* from PostgreSQL. I have been looking through the docs and they don't specify these granular offsets in the docs, but the docs are mostly concerned with what PostgreSQL accepts through its SQL parser. Is it a PostgreSQL bug that they generate them? It is reasonable in its own way, so I dunno about that.
