### ISSUE TITLE
Feature request: mechanism for creating indexes concurrently

### ISSUE THREAD

**Issue by liminalisht** [flipstone/orville#140]
The existing mechanism for creating an index in `orville` using the `Index` constructor of `SchemaItem` is a common foot-gun for developers on our team, as this mechanism of creating an index will lock out concurrent selects, inserts, updates, and deletes on the table in question. On large tables, this can be especially problematic.

Developers on our team would benefit from an additional constructor on `SchemaItem` (e.g. `ConcurrentIndex`) that would cause the index to be created concurrently.

**Comment by telser** [comment]
This is an interesting one. Looking over the docs at https://www.postgresql.org/docs/13/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY it appears these cannot be done in a transaction. Which means we can't simply add it to the normal `SchemaItem` processing for migrations. There are some ideas around being able to at least provide this functionality though. Just might need some more thought around how exactly we can get there.

**Comment by telser** [comment]
This was fixed in #175 and the drop index side was in #176.
