### ISSUE TITLE
Drop index if exists

### ISSUE THREAD

**Issue by liminalisht** [flipstone/orville#141]
Migrations that include `DropIndex` will fail if any of the columns that the index in question references have already been dropped. This is because when one drops a column in postgresql, postgres will also drop indexes and constraints on your behalf.

Consider amending `DropIndex` to perform a `DROP INDEX IF EXISTS`.

**Comment by telser** [comment]
Thanks for the report. I think we should be able to get this in the stable branch relatively easily.
