### ISSUE TITLE
Row locking select options

### ISSUE THREAD

**Issue by aaronallen8455** [flipstone/orville#340]
It would be nice to have `SelectOptions` support some of the row-level locking clauses that postgres offers, perhaps just `FOR UPDATE` if nothing else.

**Comment by qxjit** [comment]
This is a great suggestion. I've added to our list of things to do before a next release.

**Comment by telser** [comment]
@aaronallen8455 Support for row locking is added to selection options in c231aa12066e0a04b590b871dd768f1513ef591b. I think we should be good to close this issue, does that seem reasonable to you?

**Comment by aaronallen8455** [comment]
Yes, thanks @telser!
