### ISSUE TITLE
Why is `resolveOne` private?

### ISSUE THREAD

**Issue by ysangkok** [flipstone/orville#364]
It seems odd that there are `@since` annotations on private funtions like `resolveOne`. Why isn't it exported anyway? Doesn't seem like it is unsafe.

**Comment by jlavelle** [comment]
1. It forces you instantiate the `scope` type parameter to `Execute`, which limits the usefulness of the `Plan` (you can never call `planMany` or `explain` on it, for example)

2.  It allows you to construct `Plan`s that run `n+1` queries:
```
bind (planList planA) (traverse mkPlanB . resolveOne)
```

**Comment by ysangkok** [comment]
I have the following function, but I'd prefer to call `execute` only once. So essentially I want to rewrite it as returning a plan instead of using `MonadOrville`.

```
executePlans ::
  MonadOrville m => 
  Plan Plan.Execute () (Maybe a) ->
  (a -> Plan Plan.Execute () [b]) ->
  m (Maybe [b])
executePlans plan1 plan2 = do
  acls <- Plan.execute plan1 ()
  case acls of
    Nothing -> pure Nothing
    Just groups ->
      Just <$> Plan.execute (plan2 groups) ()
```

Owen and I took a stab at it and we got stuck with this:

```
executePlans =
  Plan.execute combined ()
    where
      combined = Plan.bind plan1 (fun plan2 . Plan.resolveOne)

      fun :: (a -> Plan Plan.Execute () b) -> Maybe a -> Plan Plan.Execute () (Maybe b)
      fun plan2 result =
              case result of
                Nothing -> pure Nothing
                Just groups ->
                  Just <$> plan2 groups
```

Maybe it just isn't possible to write this without two calls to execute? I wonder how we could make this more clears to users like Owen and I.

**Comment by jlavelle** [comment]
You'd need to rewrite your `plan2` as a `Plan s a [b]`, instead of a function that produces a `Plan`. That way you can use the `Plan` API to compose the plans. Is there some reason why `a` is a function argument and not a parameter to the `Plan`? If so, you may have to write a custom `Operation` to accomplish what you want, but it is generally possible.

Assuming you rewrite the `Plan`, you can just write `Plan.chain plan1 (Plan.planMaybe plan2)`.

**Comment by ysangkok** [comment]
Ok, not sure that there is a reason it's using units but I'll try migrating away from them.
