### ISSUE TITLE
"PostgresSQL" typo

### ISSUE THREAD

**Issue by tfausak** [flipstone/orville#60]
The PostgreSQL module has a typo in its name. It has an extra "s" just before "SQL".

https://github.com/flipstone/orville/blob/88f55482d3efae28c53965a525cc208f2ceb2f63/src/Database/Orville/PostgresSQL.hs#L7

[PostgreSQL](https://www.postgresql.org) is "Postgre-SQL", not "Postgres-SQL". For example, HDBC-postgresql provides [`Database.HDBC.PostgreSQL`](https://hackage.haskell.org/package/HDBC-postgresql-2.3.2.6/docs/Database-HDBC-PostgreSQL.html).

**Comment by telser** [comment]
This has driven me nuts for awhile now. I thought we had fixed it in the 0.9 branch, but apparently not.

**Comment by qxjit** [comment]
@telser While we're working on the ODBC branch is probably a good time to sneak this in finally as well.

**Comment by qxjit** [comment]
Closing this as addressed in #63
